// ============================================================
// NLLS — Demo Users for Temporary Login System (V1)
// ============================================================
// This file is TEMPORARY and will be replaced with real Supabase Auth

import type { AuthUser, UserRoleType } from '@/types';
import { PERMISSIONS } from '@/lib/auth/permissions';

const ALL_PERMISSIONS = Object.values(PERMISSIONS);

const TEACHER_PERMISSIONS = [
  PERMISSIONS.VIEW_ATTENDANCE,
  PERMISSIONS.EDIT_ATTENDANCE,
  PERMISSIONS.VIEW_EXAMS,
  PERMISSIONS.CREATE_EXAMS,
  PERMISSIONS.ENTER_EXAM_RESULTS,
  PERMISSIONS.CREATE_INCIDENTS,
  PERMISSIONS.MANAGE_ASSIGNMENTS,
  PERMISSIONS.MANAGE_MATERIALS,
];

const SUPERVISOR_PERMISSIONS = [
  PERMISSIONS.VIEW_STUDENTS,
  PERMISSIONS.VIEW_PARENTS,
  PERMISSIONS.VIEW_TEACHERS,
  PERMISSIONS.VIEW_ATTENDANCE,
  PERMISSIONS.EDIT_ATTENDANCE,
  PERMISSIONS.VIEW_EXAMS,
  PERMISSIONS.CREATE_EXAMS,
  PERMISSIONS.EDIT_EXAMS,
  PERMISSIONS.ENTER_EXAM_RESULTS,
  PERMISSIONS.EDIT_EXAM_RESULTS,
  PERMISSIONS.PUBLISH_EXAM_RESULTS,
  PERMISSIONS.VIEW_INCIDENTS,
  PERMISSIONS.CREATE_INCIDENTS,
  PERMISSIONS.MANAGE_ASSIGNMENTS,
  PERMISSIONS.MANAGE_MATERIALS,
  PERMISSIONS.VIEW_ANALYTICS,
];

const ADMIN_PERMISSIONS = [
  PERMISSIONS.VIEW_STUDENTS,
  PERMISSIONS.CREATE_STUDENTS,
  PERMISSIONS.EDIT_STUDENTS,
  PERMISSIONS.VIEW_PARENTS,
  PERMISSIONS.CREATE_PARENTS,
  PERMISSIONS.EDIT_PARENTS,
  PERMISSIONS.VIEW_TEACHERS,
  PERMISSIONS.MANAGE_TEACHERS,
  PERMISSIONS.VIEW_ATTENDANCE,
  PERMISSIONS.EDIT_ATTENDANCE,
  PERMISSIONS.VIEW_EXAMS,
  PERMISSIONS.CREATE_EXAMS,
  PERMISSIONS.EDIT_EXAMS,
  PERMISSIONS.ENTER_EXAM_RESULTS,
  PERMISSIONS.EDIT_EXAM_RESULTS,
  PERMISSIONS.PUBLISH_EXAM_RESULTS,
  PERMISSIONS.EDIT_WEBSITE,
  PERMISSIONS.MANAGE_GALLERY,
  PERMISSIONS.MANAGE_NEWS,
  PERMISSIONS.MANAGE_EVENTS,
  PERMISSIONS.MANAGE_PAGES,
  PERMISSIONS.MANAGE_ADMISSIONS_CONTENT,
  PERMISSIONS.MANAGE_ACCOUNTS,
  PERMISSIONS.GENERATE_ACCOUNTS,
  PERMISSIONS.RESET_PASSWORDS,
  PERMISSIONS.VIEW_CREDENTIALS,
  PERMISSIONS.PRINT_CREDENTIALS,
  PERMISSIONS.VIEW_INCIDENTS,
  PERMISSIONS.CREATE_INCIDENTS,
  PERMISSIONS.MANAGE_DISCIPLINE,
  PERMISSIONS.MANAGE_ADMISSIONS,
  PERMISSIONS.MANAGE_TIMETABLE,
  PERMISSIONS.MANAGE_SUBJECTS,
  PERMISSIONS.MANAGE_CLASSES,
  PERMISSIONS.MANAGE_ANNOUNCEMENTS,
  PERMISSIONS.MANAGE_EMAIL,
  PERMISSIONS.VIEW_EMAIL_LOGS,
  PERMISSIONS.MANAGE_MATERIALS,
  PERMISSIONS.MANAGE_ASSIGNMENTS,
  PERMISSIONS.MANAGE_REQUESTS,
  PERMISSIONS.MANAGE_DOCUMENTS,
  PERMISSIONS.GENERATE_REPORT_CARDS,
  PERMISSIONS.VIEW_ANALYTICS,
  PERMISSIONS.MANAGE_CALENDAR,
  PERMISSIONS.MANAGE_MEDIA,
  PERMISSIONS.MANAGE_GRADING_CONFIG,
];

const HEAD_ADMIN_PERMISSIONS = [
  ...ADMIN_PERMISSIONS,
  PERMISSIONS.DELETE_STUDENTS,
  PERMISSIONS.PUBLISH_FINAL_EXAM_RESULTS,
  PERMISSIONS.REOPEN_EXAM_RESULTS,
  PERMISSIONS.APPROVE_SUSPENSION,
  PERMISSIONS.VIEW_FINANCE,
  PERMISSIONS.MANAGE_FINANCE,
  PERMISSIONS.MANAGE_ROLES,
  PERMISSIONS.MANAGE_PERMISSIONS,
  PERMISSIONS.VIEW_AUDIT_LOGS,
  PERMISSIONS.MANAGE_SETTINGS,
  PERMISSIONS.MANAGE_ACADEMIC_YEARS,
  PERMISSIONS.PROMOTE_STUDENTS,
];

export const DEMO_USERS: Record<UserRoleType, AuthUser> = {
  student: {
    id: 'demo-student-001',
    email: 'ahmed.khalil@nlls.com',
    profile: {
      id: 'demo-student-001',
      email: 'ahmed.khalil@nlls.com',
      first_name: 'Ahmed',
      last_name: 'Khalil',
      first_name_ar: 'أحمد',
      last_name_ar: 'خليل',
      role_type: 'student',
      is_active: true,
      requires_password_change: false,
      created_at: '2026-09-01T00:00:00Z',
      updated_at: '2026-09-01T00:00:00Z',
    },
    role: 'student',
    permissions: [],
  },
  parent: {
    id: 'demo-parent-001',
    email: 'mohammed.khalil@nlls.com',
    profile: {
      id: 'demo-parent-001',
      email: 'mohammed.khalil@nlls.com',
      first_name: 'Mohammed',
      last_name: 'Khalil',
      first_name_ar: 'محمد',
      last_name_ar: 'خليل',
      role_type: 'parent',
      is_active: true,
      requires_password_change: false,
      created_at: '2026-09-01T00:00:00Z',
      updated_at: '2026-09-01T00:00:00Z',
    },
    role: 'parent',
    permissions: [],
  },
  teacher: {
    id: 'demo-teacher-001',
    email: 'sarah.hassan@nlls.com',
    profile: {
      id: 'demo-teacher-001',
      email: 'sarah.hassan@nlls.com',
      first_name: 'Sarah',
      last_name: 'Hassan',
      first_name_ar: 'سارة',
      last_name_ar: 'حسن',
      role_type: 'teacher',
      is_active: true,
      requires_password_change: false,
      created_at: '2026-09-01T00:00:00Z',
      updated_at: '2026-09-01T00:00:00Z',
    },
    role: 'teacher',
    permissions: TEACHER_PERMISSIONS,
  },
  supervisor: {
    id: 'demo-supervisor-001',
    email: 'fatima.ali@nlls.com',
    profile: {
      id: 'demo-supervisor-001',
      email: 'fatima.ali@nlls.com',
      first_name: 'Fatima',
      last_name: 'Ali',
      first_name_ar: 'فاطمة',
      last_name_ar: 'علي',
      role_type: 'supervisor',
      is_active: true,
      requires_password_change: false,
      created_at: '2026-09-01T00:00:00Z',
      updated_at: '2026-09-01T00:00:00Z',
    },
    role: 'supervisor',
    permissions: SUPERVISOR_PERMISSIONS,
  },
  admin: {
    id: 'demo-admin-001',
    email: 'omar.mahmoud@nlls.com',
    profile: {
      id: 'demo-admin-001',
      email: 'omar.mahmoud@nlls.com',
      first_name: 'Omar',
      last_name: 'Mahmoud',
      first_name_ar: 'عمر',
      last_name_ar: 'محمود',
      role_type: 'admin',
      is_active: true,
      requires_password_change: false,
      created_at: '2026-09-01T00:00:00Z',
      updated_at: '2026-09-01T00:00:00Z',
    },
    role: 'admin',
    permissions: ADMIN_PERMISSIONS,
  },
  head_admin: {
    id: 'demo-headmin-001',
    email: 'nadia.ibrahim@nlls.com',
    profile: {
      id: 'demo-headmin-001',
      email: 'nadia.ibrahim@nlls.com',
      first_name: 'Nadia',
      last_name: 'Ibrahim',
      first_name_ar: 'نادية',
      last_name_ar: 'إبراهيم',
      role_type: 'head_admin',
      is_active: true,
      requires_password_change: false,
      created_at: '2026-09-01T00:00:00Z',
      updated_at: '2026-09-01T00:00:00Z',
    },
    role: 'head_admin',
    permissions: HEAD_ADMIN_PERMISSIONS,
  },
  developer: {
    id: 'demo-dev-001',
    email: 'marksamer010@gmail.com',
    profile: {
      id: 'demo-dev-001',
      email: 'marksamer010@gmail.com',
      first_name: 'Mark',
      last_name: 'Samer',
      role_type: 'developer',
      is_active: true,
      requires_password_change: false,
      created_at: '2026-09-01T00:00:00Z',
      updated_at: '2026-09-01T00:00:00Z',
    },
    role: 'developer',
    permissions: ALL_PERMISSIONS,
  },
};

// Role display configuration
export const ROLE_CONFIG: Record<
  UserRoleType,
  { label: string; description: string; color: string; icon: string }
> = {
  student: {
    label: 'Student',
    description: 'Access your classes, grades, and assignments',
    color: '#3b82f6',
    icon: '🎓',
  },
  parent: {
    label: 'Parent',
    description: "Monitor your children's academic progress",
    color: '#10b981',
    icon: '👨‍👩‍👧‍👦',
  },
  teacher: {
    label: 'Teacher',
    description: 'Manage classes, grades, and attendance',
    color: '#8b5cf6',
    icon: '👩‍🏫',
  },
  supervisor: {
    label: 'Supervisor',
    description: 'Oversee teachers and academic performance',
    color: '#f59e0b',
    icon: '📋',
  },
  admin: {
    label: 'Admin',
    description: 'Manage school operations and data',
    color: '#ef4444',
    icon: '⚙️',
  },
  head_admin: {
    label: 'Head Admin',
    description: 'Full administrative control and oversight',
    color: '#dc2626',
    icon: '🏛️',
  },
  developer: {
    label: 'Developer',
    description: 'System development and configuration',
    color: '#6b7280',
    icon: '💻',
  },
};
