// ============================================================
// NLLS — Portal Navigation Configuration
// ============================================================

import type { UserRoleType, NavItem } from '@/types';
import { PERMISSIONS } from '@/lib/auth/permissions';

// Icons are Lucide React icon names
export const PORTAL_NAV: Record<UserRoleType, NavItem[]> = {
  student: [
    { label: 'Dashboard', href: '/portal/dashboard', icon: 'LayoutDashboard' },
    { label: 'My Classes', href: '/portal/my-classes', icon: 'School' },
    { label: 'Subjects', href: '/portal/subjects', icon: 'BookOpen' },
    { label: 'Timetable', href: '/portal/timetable', icon: 'Calendar' },
    { label: 'Homework', href: '/portal/homework', icon: 'ClipboardList' },
    { label: 'Exams', href: '/portal/exams', icon: 'FileText' },
    { label: 'Grades', href: '/portal/grades', icon: 'Award' },
    { label: 'Attendance', href: '/portal/attendance', icon: 'CheckSquare' },
    { label: 'Materials', href: '/portal/materials', icon: 'FolderOpen' },
    { label: 'Calendar', href: '/portal/calendar', icon: 'CalendarDays' },
    { label: 'Announcements', href: '/portal/announcements', icon: 'Megaphone' },
    { label: 'Messages', href: '/portal/messages', icon: 'Mail' },
    { label: 'Profile', href: '/portal/profile', icon: 'User' },
  ],

  parent: [
    { label: 'Dashboard', href: '/portal/dashboard', icon: 'LayoutDashboard' },
    { label: 'My Children', href: '/portal/my-children', icon: 'Users' },
    { label: 'Academic Results', href: '/portal/results', icon: 'Award' },
    { label: 'Exams', href: '/portal/exams', icon: 'FileText' },
    { label: 'Attendance', href: '/portal/attendance', icon: 'CheckSquare' },
    { label: 'Homework', href: '/portal/homework', icon: 'ClipboardList' },
    { label: 'Timetable', href: '/portal/timetable', icon: 'Calendar' },
    { label: 'Calendar', href: '/portal/calendar', icon: 'CalendarDays' },
    { label: 'Announcements', href: '/portal/announcements', icon: 'Megaphone' },
    { label: 'Messages', href: '/portal/messages', icon: 'Mail' },
    { label: 'Requests', href: '/portal/requests', icon: 'Send' },
    { label: 'Documents', href: '/portal/documents', icon: 'FileArchive' },
    { label: 'Profile', href: '/portal/profile', icon: 'User' },
  ],

  teacher: [
    { label: 'Dashboard', href: '/portal/dashboard', icon: 'LayoutDashboard' },
    { label: 'My Classes', href: '/portal/my-classes', icon: 'School' },
    { label: 'Students', href: '/portal/students', icon: 'Users' },
    { label: 'Attendance', href: '/portal/attendance', icon: 'CheckSquare', permission: PERMISSIONS.EDIT_ATTENDANCE },
    { label: 'Homework', href: '/portal/homework', icon: 'ClipboardList', permission: PERMISSIONS.MANAGE_ASSIGNMENTS },
    { label: 'Exams', href: '/portal/exams', icon: 'FileText', permission: PERMISSIONS.VIEW_EXAMS },
    { label: 'Grades', href: '/portal/grades', icon: 'Award', permission: PERMISSIONS.ENTER_EXAM_RESULTS },
    { label: 'Materials', href: '/portal/materials', icon: 'FolderOpen', permission: PERMISSIONS.MANAGE_MATERIALS },
    { label: 'Calendar', href: '/portal/calendar', icon: 'CalendarDays' },
    { label: 'Announcements', href: '/portal/announcements', icon: 'Megaphone' },
    { label: 'Messages', href: '/portal/messages', icon: 'Mail' },
  ],

  supervisor: [
    { label: 'Dashboard', href: '/portal/dashboard', icon: 'LayoutDashboard' },
    { label: 'Teachers', href: '/portal/teachers', icon: 'UserCheck', permission: PERMISSIONS.VIEW_TEACHERS },
    { label: 'Classes', href: '/portal/classes', icon: 'School' },
    { label: 'Students', href: '/portal/students', icon: 'Users', permission: PERMISSIONS.VIEW_STUDENTS },
    { label: 'Exams', href: '/portal/exams', icon: 'FileText', permission: PERMISSIONS.VIEW_EXAMS },
    { label: 'Performance', href: '/portal/performance', icon: 'TrendingUp', permission: PERMISSIONS.VIEW_ANALYTICS },
    { label: 'Attendance', href: '/portal/attendance', icon: 'CheckSquare', permission: PERMISSIONS.VIEW_ATTENDANCE },
    { label: 'Curriculum', href: '/portal/curriculum', icon: 'BookOpen' },
    { label: 'Reports', href: '/portal/reports', icon: 'BarChart3' },
    { label: 'Approvals', href: '/portal/approvals', icon: 'CheckCircle' },
    { label: 'Messages', href: '/portal/messages', icon: 'Mail' },
  ],

  admin: [
    { label: 'Dashboard', href: '/portal/dashboard', icon: 'LayoutDashboard' },
    { label: 'Students', href: '/portal/students', icon: 'Users', permission: PERMISSIONS.VIEW_STUDENTS },
    { label: 'Parents', href: '/portal/parents', icon: 'UserPlus', permission: PERMISSIONS.VIEW_PARENTS },
    { label: 'Teachers', href: '/portal/teachers', icon: 'UserCheck', permission: PERMISSIONS.VIEW_TEACHERS },
    { label: 'Supervisors', href: '/portal/supervisors', icon: 'Shield' },
    { label: 'Classes', href: '/portal/classes', icon: 'School', permission: PERMISSIONS.MANAGE_CLASSES },
    { label: 'Subjects', href: '/portal/subjects', icon: 'BookOpen', permission: PERMISSIONS.MANAGE_SUBJECTS },
    { label: 'Timetable', href: '/portal/timetable', icon: 'Calendar', permission: PERMISSIONS.MANAGE_TIMETABLE },
    { label: 'Attendance', href: '/portal/attendance', icon: 'CheckSquare', permission: PERMISSIONS.VIEW_ATTENDANCE },
    { label: 'Exams', href: '/portal/exams', icon: 'FileText', permission: PERMISSIONS.VIEW_EXAMS },
    { label: 'Grades', href: '/portal/grades', icon: 'Award' },
    { label: 'Student Affairs', href: '/portal/student-affairs', icon: 'AlertTriangle', permission: PERMISSIONS.VIEW_INCIDENTS },
    { label: 'Admissions', href: '/portal/admissions', icon: 'UserPlus2', permission: PERMISSIONS.MANAGE_ADMISSIONS },
    { label: 'Messages', href: '/portal/messages', icon: 'Mail' },
    { label: 'Events', href: '/portal/events', icon: 'CalendarDays', permission: PERMISSIONS.MANAGE_EVENTS },
    { label: 'Announcements', href: '/portal/announcements', icon: 'Megaphone', permission: PERMISSIONS.MANAGE_ANNOUNCEMENTS },
    { label: 'Website', href: '/portal/website', icon: 'Globe', permission: PERMISSIONS.EDIT_WEBSITE },
    { label: 'Documents', href: '/portal/documents', icon: 'FileArchive', permission: PERMISSIONS.MANAGE_DOCUMENTS },
    { label: 'Requests', href: '/portal/requests', icon: 'Send', permission: PERMISSIONS.MANAGE_REQUESTS },
    { label: 'Reports', href: '/portal/reports', icon: 'BarChart3', permission: PERMISSIONS.VIEW_ANALYTICS },
    { label: 'Accounts', href: '/portal/accounts', icon: 'Key', permission: PERMISSIONS.MANAGE_ACCOUNTS },
    { label: 'Email Center', href: '/portal/email', icon: 'Mail', permission: PERMISSIONS.MANAGE_EMAIL },
    { label: 'Analytics', href: '/portal/analytics', icon: 'TrendingUp', permission: PERMISSIONS.VIEW_ANALYTICS },
  ],

  head_admin: [
    { label: 'Dashboard', href: '/portal/dashboard', icon: 'LayoutDashboard' },
    { label: 'Students', href: '/portal/students', icon: 'Users' },
    { label: 'Parents', href: '/portal/parents', icon: 'UserPlus' },
    { label: 'Teachers', href: '/portal/teachers', icon: 'UserCheck' },
    { label: 'Supervisors', href: '/portal/supervisors', icon: 'Shield' },
    { label: 'Classes', href: '/portal/classes', icon: 'School' },
    { label: 'Subjects', href: '/portal/subjects', icon: 'BookOpen' },
    { label: 'Timetable', href: '/portal/timetable', icon: 'Calendar' },
    { label: 'Attendance', href: '/portal/attendance', icon: 'CheckSquare' },
    { label: 'Exams', href: '/portal/exams', icon: 'FileText' },
    { label: 'Grades', href: '/portal/grades', icon: 'Award' },
    { label: 'Student Affairs', href: '/portal/student-affairs', icon: 'AlertTriangle' },
    { label: 'Admissions', href: '/portal/admissions', icon: 'UserPlus2' },
    { label: 'Messages', href: '/portal/messages', icon: 'Mail' },
    { label: 'Events', href: '/portal/events', icon: 'CalendarDays' },
    { label: 'Announcements', href: '/portal/announcements', icon: 'Megaphone' },
    { label: 'Website', href: '/portal/website', icon: 'Globe' },
    { label: 'Documents', href: '/portal/documents', icon: 'FileArchive' },
    { label: 'Requests', href: '/portal/requests', icon: 'Send' },
    { label: 'Reports', href: '/portal/reports', icon: 'BarChart3' },
    { label: 'Accounts', href: '/portal/accounts', icon: 'Key' },
    { label: 'Email Center', href: '/portal/email', icon: 'Mail' },
    { label: 'Analytics', href: '/portal/analytics', icon: 'TrendingUp' },
    { label: 'Permissions', href: '/portal/permissions', icon: 'Lock', permission: PERMISSIONS.MANAGE_PERMISSIONS },
    { label: 'Settings', href: '/portal/settings', icon: 'Settings', permission: PERMISSIONS.MANAGE_SETTINGS },
    { label: 'Audit Logs', href: '/portal/audit-logs', icon: 'FileSearch', permission: PERMISSIONS.VIEW_AUDIT_LOGS },
  ],

  developer: [
    { label: 'Dashboard', href: '/portal/dashboard', icon: 'LayoutDashboard' },
    { label: 'Students', href: '/portal/students', icon: 'Users' },
    { label: 'Parents', href: '/portal/parents', icon: 'UserPlus' },
    { label: 'Teachers', href: '/portal/teachers', icon: 'UserCheck' },
    { label: 'Supervisors', href: '/portal/supervisors', icon: 'Shield' },
    { label: 'Classes', href: '/portal/classes', icon: 'School' },
    { label: 'Subjects', href: '/portal/subjects', icon: 'BookOpen' },
    { label: 'Timetable', href: '/portal/timetable', icon: 'Calendar' },
    { label: 'Attendance', href: '/portal/attendance', icon: 'CheckSquare' },
    { label: 'Exams', href: '/portal/exams', icon: 'FileText' },
    { label: 'Grades', href: '/portal/grades', icon: 'Award' },
    { label: 'Student Affairs', href: '/portal/student-affairs', icon: 'AlertTriangle' },
    { label: 'Admissions', href: '/portal/admissions', icon: 'UserPlus2' },
    { label: 'Messages', href: '/portal/messages', icon: 'Mail' },
    { label: 'Events', href: '/portal/events', icon: 'CalendarDays' },
    { label: 'Announcements', href: '/portal/announcements', icon: 'Megaphone' },
    { label: 'Website', href: '/portal/website', icon: 'Globe' },
    { label: 'Documents', href: '/portal/documents', icon: 'FileArchive' },
    { label: 'Requests', href: '/portal/requests', icon: 'Send' },
    { label: 'Reports', href: '/portal/reports', icon: 'BarChart3' },
    { label: 'Accounts', href: '/portal/accounts', icon: 'Key' },
    { label: 'Email Center', href: '/portal/email', icon: 'Mail' },
    { label: 'Analytics', href: '/portal/analytics', icon: 'TrendingUp' },
    { label: 'Permissions', href: '/portal/permissions', icon: 'Lock' },
    { label: 'Settings', href: '/portal/settings', icon: 'Settings' },
    { label: 'Audit Logs', href: '/portal/audit-logs', icon: 'FileSearch' },
    { label: 'System', href: '/portal/system', icon: 'Terminal' },
  ],
};

// Role label mapping
export const ROLE_LABELS: Record<UserRoleType, string> = {
  student: 'Student',
  parent: 'Parent',
  teacher: 'Teacher',
  supervisor: 'Supervisor',
  admin: 'Administrator',
  head_admin: 'Head Administrator',
  developer: 'Developer',
};
